export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Busque por inspirações",
  headline: "Mantenha streaks",
  description:
    "Streak é a quantidade de vezes seguidas que você realizou uma atividade. É aquela série de vitórias na manutenção dos bons hábitos",
  buttonLabel: "Faça parte",
  imgStart: false,
  img: require("../../Images/svg-1.svg").default,
  alt: "Motivation",
  dark: true,
  primary: false,
  darkText: false,
  topLineText: true,
  btnLink: "signup",
  btnLinkR: false,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: true,
  lightTextDesc: false,
  topLine: "Mudanças",
  headline: "Foque no longo prazo e celebre",
  description:
    "Para manter a determinação, uma ótima ideia é dividir o caminho em etapas, comemorando a conquista de cada uma pequena vitória. ",
  buttonLabel: "Saiba Mais",
  imgStart: true,
  img: require("../../Images/svg-2.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  topLineText: false,
  btnLink: "services",
  btnLinkR: false,
};

export const homeObjThree = {
  id: "signup",
  lightBg: true,
  lightText: true,
  lightTextDesc: false,
  topLine: "Entre para o nosso time",
  headline: "Criar uma conta é extremamente facil",
  description:
    "tenha tudo configurado e pronto em menos de 10 minutos. Tudo que você precisa fazer é adicionar suas informações e você está pronto.",
  buttonLabel: "Começe agora",
  imgStart: false,
  img: require("../../Images/svg-4.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  topLineText: false,
  btnLink: "/register",
  btnLinkR: true,
};
